#!/bin/bash

# Scripts for Linux - publicIP
# Copyright (C) 2019 - 2020 Alejandro López

clear
OLDIP=$(cat ip)
IPACTUAL=$(curl ifconfig.me)

if [[ $OLDIP != $IPACTUAL ]]; then
  echo "La ip ahora es: $IPACTUAL " | mail -s "La ip publica a cambiado." alejandrolopezfuentes789@gmail.com
  echo $IPACTUAL > ip
fi

clear
